### ISSUE TITLE
Set Battery Max Charge Current can't be set to 0 anymore

### ISSUE THREAD

**Issue by bbrodnik** [heszegi/com.heszi.deye#6]
A have Set Battery Max Charge Current card in flow for a while, but after some other changes in flow I can't save it any more due to Invalid arguments error in mentioned card. I don't understand why since it worked, until last update, I think.
![2024-11-05_10-37-36](https://github.com/user-attachments/assets/65752efa-35cf-4ce0-b3c8-b74e21230308)

**Comment by heszegi** [comment]
I'm sorry to hear about this issue. Unfortunately, I'm not sure why it happened, but I can confirm that the minimum value for this setting is 1 and hasn’t changed since this card added in the previous version of the app. It’s likely that an error occurred in Homey base system during the app update, causing the value to reset to 0. Please try deleting the card and adding it again with a valid value. 

Please let me know the result

**Comment by bbrodnik** [comment]
The minimum value for this setting should be 0 to disable charging, not 1.  It was intentionally set to zero and it worked.
It doesn't matter if a delete and add the card.

**Comment by heszegi** [comment]
Hmm... that's really interesting! The minimum value has always been set to 1 in the configuration files for this card, so it must have been a bug that allowed you to set it to 0.

Your solution to disable charging/discharging sounds intriguing, though. I’ll look into it, and if it doesn’t cause any issues, I'll consider allowing a 0 setting in a future minor release.

**Comment by bbrodnik** [comment]
Manual input on inverter allows 0, so why API shouldn't?
